In [15]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
df = pd.read_csv('insurance_data.csv')

In [17]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance, test_size=0.2, random_state = 25)

In [19]:
X_train

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [20]:
len(X_train)

22

In [21]:
X_train_scaled = X_train.copy()
X_train_scaled = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [22]:
X_train_scaled

0     0.22
13    0.29
6     0.55
17    0.58
24    0.50
19    0.18
25    0.54
16    0.25
20    0.21
3     0.52
7     0.60
1     0.25
5     0.56
27    0.46
8     0.62
18    0.19
12    0.27
23    0.45
22    0.40
15    0.55
26    0.23
4     0.46
Name: age, dtype: float64

In [23]:
X_train_scaled.dtypes

dtype('float64')

In [24]:
X_train_scaled

0     0.22
13    0.29
6     0.55
17    0.58
24    0.50
19    0.18
25    0.54
16    0.25
20    0.21
3     0.52
7     0.60
1     0.25
5     0.56
27    0.46
8     0.62
18    0.19
12    0.27
23    0.45
22    0.40
15    0.55
26    0.23
4     0.46
Name: age, dtype: float64

In [25]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(1,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50


/home/kritim/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6674
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6672
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6670
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6669
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6667
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6665
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 13/50

In [26]:
model.evaluate(X_test_scaled,y_test)

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_2" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (None, 2)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 2), dtype=float32)
  • training=False
  • mask=None

In [27]:
model.predict(X_test_scaled)

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_2" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (6, 2)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(6, 2), dtype=float32)
  • training=False
  • mask=None

In [28]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [29]:
coef, intercept = model.get_weights()

In [30]:
coef, intercept

(array([[1.0533643]], dtype=float32), array([-0.049568], dtype=float32))

In [31]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [32]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [33]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [34]:
prediction_function(.18, 1)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [35]:


def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))



array([0.99999386, 0.5       , 0.73105858])

In [36]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [37]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [38]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

KeyError: 'age'

In [39]:
coef, intercept

(array([[1.0533643]], dtype=float32), array([-0.049568], dtype=float32))

In [40]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [41]:
customModel.predict(X_test_scaled)

2     0.813057
10    0.764948
21    0.564636
11    0.782450
14    0.816078
9     0.833411
dtype: float64

In [42]:
model.predict(X_test_scaled)

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_2" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (6, 2)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(6, 2), dtype=float32)
  • training=False
  • mask=None