In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


In [2]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error: ", total_error)

    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [3]:
mae(y_true, y_predicted)

Total error:  2.5
MAE: 0.5


0.5

In [5]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [7]:
np.log([0.000001])

array([-13.81551056])

In [8]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [9]:
mae_np(y_predicted, y_true)

0.5

In [10]:
np.log([0])

/tmp/ipykernel_13852/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [11]:
epsilon = 1e-15

In [12]:
np.log([1e-15])

array([-34.53877639])

In [13]:
y_predicted

array([1, 1, 0, 0, 1])

In [14]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [15]:
1-epsilon

0.999999999999999

In [16]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [17]:
y_predicted_new = np.array(y_predicted_new)

In [18]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [19]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [20]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [21]:
log_loss(y_true, y_predicted)

17.2696280766844